services:
  redis:
    image: redis:7
    command:
      [
        "redis-server",
        "--appendonly","yes",
        "--requirepass","JobHuntly123"
      ]
    networks:
      - job-huntly-network
  job-huntly-backend:
    image: huynguyen1911/job-huntly-backend:prod-v1
    env_file:
      - .env.local.properties
    ports:
      - "8080:8080"
    networks:
      - job-huntly-network

networks:
  job-huntly-network:
    external: true
    name: job-huntly-network